//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitySample.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Books
    {
        public int book_id { get; set; }
        public Nullable<float> sales { get; set; }
        public string title { get; set; }
        public string author { get; set; }
        public Nullable<float> price { get; set; }
        public Nullable<bool> instore { get; set; }
        public string shipping { get; set; }
        public Nullable<bool> bestseller { get; set; }
        public string pub_date { get; set; }
        public Nullable<System.Guid> GUID { get; set; }
        public Nullable<System.DateTime> SYS_TS { get; set; }
        public string ImageUrl { get; set; }
    }
}
